cs412/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path("admin/", admin.site.urls),

    # For Google sign in
    path('accounts/', include('allauth.urls')),  

    path("quotes/", include("quotes.urls")), 
    path("restaurant/", include("restaurant.urls")), 
    path("mini_insta/", include ("mini_insta.urls")),
    path("marathon_analytics/", include ("marathon_analytics.urls")),
    path("voter_analytics/", include ("voter_analytics.urls")),
    path("dadjokes/", include ("dadjokes.urls")),
    path("project/", include("project.urls")),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_insta/urls.py
# File: urls.py 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/25/2025
# Description: Urls for the app mini_insta

from django.urls import path
# from .views import ShowAllView, RandomArticleView, ArticleView, --> from example
from .views import * 
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views 

urlpatterns = [

    path('', ProfileListView.as_view(), name="show_all_profiles"),
    path('show_all_profiles/', ProfileListView.as_view(), name="show_all_profiles"),
    path('profile/<int:pk>', ProfileDetailView.as_view(), name='profile'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post'),
    path('profile/create_post', CreatePostView.as_view(), name="create_post"),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('post/<int:pk>/update', UpdatePostView.as_view(), name='update_post'),
    path('profile/<int:pk>/followers', ShowFollowersDetailView.as_view(), name='show_followers'),
    path('profile/<int:pk>/following', ShowFollowingDetailView.as_view() , name='show_following'),
    path('profile/feed',  PostFeedListView.as_view(), name="show_feed"),
    path('profile/search', SearchView.as_view(), name='search'),

    # Authorization-related URLs (A7): 
    path('login/', auth_views.LoginView.as_view(template_name='mini_insta/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='logout_confirmation'), name='logout'),
    path('logged_out/', LogoutConfirmationView.as_view(), name='logout_confirmation'),
    path('register/', UserRegistrationView.as_view(), name='register'), 
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('profile/<int:pk>/follow/', FollowProfileView.as_view(), name='follow_profile'),
    path('profile/<int:pk>/delete_follow/', UnfollowProfileView.as_view(), name='unfollow_profile'),
    path('post/<int:pk>/like/', AddLikeView.as_view(), name='like_post'),
    path('post/<int:pk>/delete_like/', RemoveLikeView.as_view(), name='unlike_post'),

    #############################
    #API Views: 
    # path(r'api/articles/', ArticlesSerializers.as_view(), name='article_list_api'),


    #examples assigment 4: 
    # path('profile/create', CreateArticleView.as_view(), name="create_article"),
    # path('create_comment', CreateCommentView.as_view(), name="create_comment"),

    #from example: 
    # path('', RandomArticleView.as_view(), name="random"),
    # path('show_all/', ShowAllView.as_view(), name="show_all"),
    # path('article/<int:pk>', ArticleView.as_view(), name='article')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_insta/models.py
# File: models.py
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/25/2025
# Description: this file is my models for mini insta, assigment 4

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User     # for authentication 

# Create your models here.
    

class Profile(models.Model): 
    '''Model for the user profile '''

    # Define the data atributes

    username = models.TextField(blank = True)
    display_name = models.TextField(blank = True)
    bio_text = models.TextField(blank = True)
    join_date = models.DateTimeField(auto_now = True)
    profile_image_url = models.URLField(blank = True) #url as a string
    user = models.ForeignKey(User, on_delete=models.CASCADE) #Gave a value of 1 for profiles not associated with a user

    def __str__(self): 
        '''return a string representation of the model instance.'''
        return f'{self.username} joined {self.join_date}'
    
    def get_absolute_url(self): 
        '''return a URL to displya one instance of this object.'''
        return reverse('profile', kwargs={'pk': self.pk})
    
    def get_all_posts(self):
        '''Return a QuerySet of Posts about this Profile'''
        #Used the object manager to retrieve comments about this article
        
        posts = Post.objects.filter(profile=self)
        return posts
    
    def get_followers(self):
        '''Return a list of Profiles who follow this Profile.'''
        from .models import Follow
        follow_records = Follow.objects.filter(profile=self)
        followers = [follow.follower_profile for follow in follow_records]
        return followers

    def get_num_followers(self):
        '''return the count of followers.'''
        from .models import Follow
        return Follow.objects.filter(profile=self).count()

    def get_following(self):
        '''return a list of Profiles this Profile follows.'''
        from .models import Follow
        follow_records = Follow.objects.filter(follower_profile=self)
        following_profiles = [follow.profile for follow in follow_records]
        return following_profiles

    def get_num_following(self):
        '''return the count of Profiles this Profile follows.'''
        from .models import Follow
        return Follow.objects.filter(follower_profile=self).count()
    
    def get_post_feed(self):
        '''  return a list/QuerySet of Posts, specifically for the profiles being followed'''
        from .models import Follow, Post
        following = Follow.objects.filter(follower_profile=self)
        followed_profiles = [f.profile for f in following]
        feed_posts = Post.objects.filter(profile__in=followed_profiles).order_by('-timestamp')

        return feed_posts
    
    def is_followed_by(self, user):
        ''' if profile is followed by the a user'''
        follower_profile = Profile.objects.filter(user=user).first()
        if not follower_profile:
            return False
        return Follow.objects.filter(profile=self, follower_profile=follower_profile).exists()

    
class Post(models.Model): 
    '''Encapsulate the idea of a comment in an Article'''

    # data atributes for the Post:
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    caption = models.TextField(blank=False)
    timestamp = models.DateTimeField(auto_now=True) #tells when comment was written 

    def __str__(self):
        '''Return a string representation of this comment'''
        return f'{self.caption}'
    
    def get_all_photos(self):
        """Return a QuerySet of Photos for this Post, ordered by timestamp"""
        photos = Photo.objects.filter(post=self).order_by('-timestamp')
        return photos

    def get_all_comments(self):
        '''Return all comments for a this Post.'''
        from .models import Comment
        comments = Comment.objects.filter(post=self).order_by('-timestamp')
        return comments
    
    def get_likes(self):
        '''get all likes for this Post.'''
        from .models import Like
        likes =  Like.objects.filter(post=self).order_by('-timestamp')
        return likes
    
    def get_num_likes(self):
        '''return the number of likes for this Post.'''
        from .models import Like
        return Like.objects.filter(post=self).count()
    
    def is_liked_by(self, user):
        '''if post is liked by a certain user'''
        liker_profile = Profile.objects.filter(user=user).first()
        if not liker_profile:
            return False
        return Like.objects.filter(post=self, profile=liker_profile).exists()
    

class Photo(models.Model): 
    '''Encapsulate the idea of a comment in an Article'''

    # data atributes for the Photo:
    # post = models.ForeignKey(Post, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True) #tells when comment was written 
    image_url = models.URLField(blank = True)
    image_file = models.ImageField(upload_to='photos/', blank=True, null=True) # an actual image. Note: Changed the code from the example bc during deployment the images weren't showing. 

    def get_image_url(self):
        if self.image_file:
            return self.image_file.url
        return self.image_url
    
    def __str__(self):
        img = self.get_image_url()
        return f"Photo[{img}]" if img else f"Photo id={self.pk}"

        
class Follow(models.Model):
    '''Represents one Profile following another Profile.'''

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profile"  )
    follower_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="follower_profile")
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.follower_profile.username} follows {self.profile.username}"
    

class Comment(models.Model):
    '''Encapsulate the idea of a comment in a Post'''

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    timestamp = models.DateTimeField(auto_now=True) 

    def __str__(self):
        '''Return a string representation of this comment'''
        return f'{self.profile.username} commented: {self.text}'
    
class Like(models.Model):
    ''' Encapsulates the idea of one Profile providing approval of a Post'''
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True) 

    def __str__(self): 
        '''Return a string representation of this like'''
        return f'{self.profile.username}'





    


#from examples, Assingnment 4

        # class Comment(models.Model): 
        #     '''Encapsulate the idea of a comment in an Article'''

        #     # data atributes for the Comment:
        #     profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
        #     username = models.TextField(blank=False)
        #     bio_text = models.TextField(blank=False)
        #     published = models.DateTimeField(auto_now=True) #tells when comment was written 

        #     def __str__(self):
        #         '''Return a string representation of this comment'''
        #         return f'{self.text}'



# Code from the example assigment 3: 

            # class Article(models.Model): 
        #     ''' '''

        #     # Define the data atributes

        #     title = models.TextField(blank = True)
        #     author = models.TextField(blank = True)
        #     text = models.TextField(blank = True)
        #     published = models.DateTimeField(auto_now = True) 
        #     image_ulr = models.URLField(blank = True)


        #     def __str__(self): 
        #         '''return a string representation of the model isntance.'''
        #         return f'{self.title} by {self.author}'

mini_insta/forms.py
# File: forms.py 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/02/2025
# Description: forms file for the app mini_insta

from django import forms
from .models import *

class CreatePostForm(forms.ModelForm): 
        '''A form to add a comment about an article'''

        class Meta: 
                '''associate this form with a model from our database'''
                model = Post
                fields = ['caption'] #we dont want the drop down list

class UpdateProfileForm(forms.ModelForm):
        '''A form to handle or update a profile'''
        class Meta:
                '''associate this form with the Post model.'''
                model = Profile
                fields = ['display_name', 'bio_text', 'profile_image_url']  # which fields from model should we use

class UpdatePostForm(forms.ModelForm):
    '''A form to update the caption of an existing Post.'''

    class Meta:
        model = Post
        fields = ['caption']

class CreateProfileForm(forms.ModelForm):
    '''A form to create a new Profile'''

    class Meta:
        model = Profile
        fields = ['username', 'display_name', 'bio_text', 'profile_image_url']



#Examples Assignment 4:

        # class CreateArticleForm(forms.ModelForm): 
        #     """ a Form to add an article to the """

        #     class Meta:
        #         """associate this from with a model from out data base"""
        #         model = Profile
        #         fields = ['username', 'display_name', 'bio_text', 'profile_image_url']

        # class CreateCommentForm(forms.ModelForm): 
        #     '''A form to add a comment about an article'''

        #     class Meta: 
        #         '''associate this form with a model from our database'''
        #         model = Comment
        #         fields = ['profile', 'username', 'bio_text'] #deleated
        #         fields = ['username', 'bio_text'] #we dont want the drop down list

mini_insta/templates/mini_insta/base.html
<!-- mini_insta /base.html 
# File: base.html 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/25/2025
# Description: base for the app mini_insta
-->
{% load static%}

<html> 
    <head>
        <title>Our Mini_Insta</title>
        <link rel="stylesheet" href="{% static 'styles-blog.css' %}">
    </head>

    <body>
        <head>
            <h1>Insta</h1>

        </head>

        {% block content%}
        {% endblock%}
    </body>

<nav>
    <ul>
        <!-- Urls for users who are not logged in-->
        <li><a href="{% url 'show_all_profiles' %}">All Profiles</a></li>

        <!-- urls for logged in users only -->
        {% if request.user.is_authenticated %}

            <li><a href="{% url 'profile' request.user.profile_set.first.pk %}">My Profile</a></li>

            <li>
                <form action="{% url 'logout' %}" method="POST" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="link-button">Logout</button>
                </form>
            </li>

            <li><a href="{% url 'update_profile' %}">Update Profile</a></li>

            <li><a href="{% url 'create_post' %}">Create Post</a></li>

            <li><a href="{% url 'show_feed' %}">My Feed</a></li>

            <li><a href="{% url 'search' %}">Search</a></li>

        <!-- Urls for users who are not logged in-->        
        {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'create_profile' %}">Register</a></li>
        {% endif %}

    </ul>
    <hr>
    {% if request.user.is_authenticated %}
    Logged in as: {{request.user}}
    {% else %}
    Not logged in.
    {% endif %}
</nav>

</html>

mini_insta/templates/mini_insta/create_article_form.html
{% extends 'mini_insta/base.html' %}
{% block content %}

<h1>Create a new Profile</h1>

<!-- Display HTML forms-->
<form action="{% url 'create_article'%}" method = "POST">
    {{csrf_token}}
    <table> 
    {{form.as_table}}
    </table>

    <input type="submit" name="submit" values="Submit">
</form>

{% endblock %}

mini_insta/templates/mini_insta/create_post_form.html
<!-- mini_insta /create_post_form.html 
# File: create_post_form.html 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/30/2025
# Description: form to create a post for the app mini_insta
-->
<!-- Display the HTML form to create new Post on a Profile object-->
{% extends 'mini_insta/base.html' %}
{% block content %}

<h1>Create a new post</h1>

<!-- Display HTML form -->
<form action="{% url 'create_post' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <!-- Custom multi-file upload -->
    
    <h3>Add Images</h3>
    <p>    
        <input type="file" name="image_files" id="image_files" multiple>
    </p>

    <div>
        <input type="submit" name="submit" value="Submit">
        <a href="{% url 'profile' profile.pk %}">
            <button type="button">Cancel</button>
        </a>
    </div>
</form>

{% endblock%}

mini_insta/templates/mini_insta/create_profile_form.html
<!-- mini_insta/create_profile_form.html
# File: create_profile_form.html
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/25/2025
# Description: Handles registration for user
-->

{% extends 'mini_insta/base.html' %}

{% block content %}
<h1>Create a New Account</h1>

<form action="{% url 'create_profile' %}" method="POST">
    {% csrf_token %}

    <h2>User Details</h2>
    {{ user_form.as_p }}

    <hr>

    <h2>Profile Details</h2>
    {{ form.as_p }}

    <input type="submit" value="Create Account">
</form>

{% endblock %}

mini_insta/templates/mini_insta/register.html
<!-- mini_insta/register.html
# File: register.html
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/23/2025
# Description: Handles registration for new user
-->

{% extends 'mini_insta/base.html'%}

{% block content%}
<h1> Register for a new account </h1>

<form action="{% url 'register' %}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

mini_insta/templates/mini_insta/search.html
<!-- mini_insta/search.html
# File: search.html
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/17/2025
# Description: Search form for Profiles and Posts in the  mini_insta app
-->

{% extends 'mini_insta/base.html' %}
{% load static %}

{% block content %}
<main class="search-page">
    <h2>Search</h2>

    <form method="get" action="{% url 'search' %}">
        <input type="text" name="q" class="search-box" required>
        <button type="submit" class="search-btn">Search</button>
    </form>
</main>
{% endblock %}

mini_insta/templates/mini_insta/search_results.html
<!-- mini_insta/search_results.html
# File: search_results.html
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/18/2025
# Description: displays search results for profiles and posts in mini_insta
-->

{% extends 'mini_insta/base.html' %}
{% load static %}

{% block content %}
<main class="search-results-page">
    <h2>Search Results for "{{ query }}"</h2>

    <!-- back to search link -->
    <a href="{% url 'search' %}">Back to search</a>

    <!-- profiles  -->
    <section class="search-section">
        <h3>Matching Profiles</h3>
        {% if profiles %}
            {% for profile in profiles %}
                <div class="search-result-card">
                    <img src="{{ profile.profile_image_url }}" class="tiny-profile-pic">
                    <div>
                        <a href="{% url 'profile' profile.pk %}">
                            <strong>@{{profile.username}}</strong> — {{profile.display_name}}
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No profiles match your search.</p>
        {% endif %}
    </section>

    <!-- posts  -->
    <section class="search-section">
        <h3>Matching Posts</h3>

        {% if posts %}
            {% for post in posts %}
                <article class="post-card">
                    <a href="{% url 'post' post.pk %}">
                        {% if post.get_all_photos %}
                            {% if post.get_all_photos.0.image_file %}
                                <img src="{{ post.get_all_photos.0.image_file.url }}" alt="Post image">
                            {% elif post.get_all_photos.0.image_url %}
                                <img src="{{ post.get_all_photos.0.image_url }}" alt="Post image">
                            {% else %}
                                <img src="{% static 'images/no_image.png' %}" alt="No image available">
                            {% endif %}
                        {% else %}
                            <img src="{% static 'images/no_image.png' %}" alt="No image available">
                        {% endif %}
                    </a>

                    <h4>{{ post.caption }}</h4>
                    <p><em>Posted at {{ post.timestamp }}</em></p>
                </article>
            {% endfor %}
        {% else %}
            <p>No posts match your search.</p>
        {% endif %}
    </section>


</main>
{% endblock %}

mini_insta/templates/mini_insta/show_all.html
<!-- mini_insta /show_all.html -->
{% extends 'mini_insta/base.html '%}

{% block content %}
<h1>Showing all articles</h1>

<!-- displays a QuerySet of all articles-->
<!--{{articles}}-->

<main class="grid-container">
    <!-- scriptlet code for a loop-->
    {% for article in articles %}
    <article>
        <div> 
            <h2>{{article.title}}</h2>
            <h3>by {{article.author}}</h3>

            <p>
                {{article.text}}
            </p>
        </div>

        <img src="{{article.image_url}}" alt=""> 

    </article> 
    <hr>
    {% endfor %}
</main>

{% endblock %}

mini_insta/templates/mini_insta/show_all_profiles.html
<!-- mini_insta /show_all_profiles.html 
# File: show_all_profiles.html 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/25/2025
# Description: all profiles for the app mini_insta
-->

{% extends 'mini_insta/base.html'%}

{% block content %}
<h1>Profiles</h1>

<!-- <nav>
    <ul>
        <li><a href="{% url 'show_all_profiles' %}">All Profiles</a></li>
        I put the navegation link on top as it makes more sense, and on the footer per the instrucitons.
    </ul>
</nav> -->

<!-- displays a QuerySet of all profiles-->
<!-- {{profiles}}-->

<main class="grid-container">
    <!-- scriptlet code for a loop -->
    {% for profile in profiles %}
    <article>
        <div> 
            <h2>{{profile.username}}</h2>
            <h3>by {{profile.display_name}}</h3>

            <!-- <p>
                {{profile.bio_text}} 
            </p> -->
        </div>
        
        <!-- Code to link profile to image when clicked -->
        <a href = "{% url 'profile' profile.pk %}">  
        {% if profile.profile_image_url %}
            <img src="{{profile.profile_image_url}}" alt=""> 
        {% elif profile.profile_image_file %}
            <img src="{{profile.profile_image_file.url}}" alt=""> <!-- code to to display the image from file-->
        {% else %}
            <h3>No Image</h3>
        {% endif %}
        </a>

    </article> 
    {% endfor %}
</main>

{% endblock %} 

mini_insta/templates/mini_insta/show_feed.html
<!-- mini_insta/show_feed.html 
# File: show_feed.html 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/17/2025
# Description: displays the post feed for a single Profile in mini_insta
-->

{% extends 'mini_insta/base.html' %}
{% load static %}

{% block content %}

<main class="feed-page">
    <!-- using classes so my css can handle styling -->

    <section class="feed-header">
        <h2>{{ profile.username }}’s Feed</h2>

        <a href="{% url 'profile' profile.pk %}">
            <img src="{% static 'images/back_to_profile_icon.png' %}" width="150">
        </a>
    </section>

    <!-- Display the posts from followed profiles -->
    {% if posts %}
        <section class="feed-posts">
            {% for post in posts %}
                <article class="feed-post-card">
                    
                    <!-- profile info -->
                    <div class="post-header">
                        <img src="{{ post.profile.profile_image_url }}" class="tiny-profile-pic">
                        <div class="post-user-info">
                            <strong>@{{ post.profile.username }}</strong><br>
                            <span>{{ post.profile.display_name }}</span>
                        </div>
                    </div>

                    <div class="post-image">
                        {% if post.get_all_photos %}
                            {% if post.get_all_photos.0.image_file %}
                                <img src="{{ post.get_all_photos.0.image_file.url }}" alt="Post image" class="feed-post-image">
                            {% elif post.get_all_photos.0.image_url %}
                                <img src="{{ post.get_all_photos.0.image_url }}" alt="Post image" class="feed-post-image">
                            {% else %}
                                <img src="{% static 'images/no_image.png' %}" alt="No image" class="feed-post-image">
                            {% endif %}
                        {% else %}
                            <img src="{% static 'images/no_image.png' %}" alt="No image" class="feed-post-image">
                        {% endif %}
                    </div>

                    <div class="post-caption">
                        <p>{{ post.caption }}</p>
                        <p><em>Posted at {{ post.timestamp }}</em></p>
                    </div>

                    <div class="post-stats">
                        <p><strong>{{ post.get_num_likes }}</strong> likes</p>
                        <p><strong>{{ post.get_all_comments|length }}</strong> comments</p>
                    </div>
                </article>
            {% endfor %}
        </section>
    {% else %}
        <p>No posts yet from profiles you follow.</p>
    {% endif %}
</main>

{% endblock %}

mini_insta/templates/mini_insta/show_following.html
<!-- mini_insta/show_following.html 
# File: show_following.html 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/14/2025
# Description: shows who the profile is following (subscriptions) for the app mini_insta
-->

{% extends 'mini_insta/base.html' %}
{% load static %}

{% block content %}

<main class="follow-page">
    <!-- using classes to delegate styling to css -->

    <section class="follow-header">
        <h2>{{ profile.username }} is following</h2>
        <p>Total Following: {{ num_following }}</p>
    </section>

    <!-- list of followed users -->
    <section class="follow-list">
        {% if following_profiles %}
            {% for followed in following_profiles %}
                <p>
                    <a href="{% url 'profile' followed.pk %}">
                        <strong>@{{ followed.username }}</strong>
                        <span>({{ followed.display_name }})</span>
                    </a>
                </p>
            {% endfor %}
        {% else %}
            <!-- in case they don't follow anyone -->
            <p>This profile isn’t following anyone yet.</p>
        {% endif %}

        <!-- back to profile icon -->
        <div style="text-align: left; margin-top: 20px;">
            <a href="{% url 'profile' profile.pk %}">
                <img src="{% static 'images/back_to_profile_icon.png' %}" alt="Back to Profile" width="100">
            </a>
        </div>
    </section>
</main>

{% endblock %}

mini_insta/templates/mini_insta/show_post.html
<!-- mini_insta /show_post.html 
# File: show_post.html 
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 09/30/2025
# Description: individual post for the app mini_insta
-->

{% extends 'mini_insta/base.html' %}
{% load static %}

{% block content%}

<main>
    <h1>{{ post.caption }}</h1>

    <!-- Delete/Update Post Link -->
    {% if request.user == post.profile.user %}
        <a href="{% url 'delete_post' post.pk %}">
            <img src="{% static 'images/delete_icon.png' %}" alt="Delete Post" width="200">
        </a>
        <a href="{% url 'update_post' post.pk %}">
            <img src="{% static 'images/update_icon.png' %}" alt="Update Post" width="200">
        </a>
    {% endif %}

    <div>
        <!-- Show all photos for this post -->
        {% for photo in post.get_all_photos %}
            {% if photo.image_file %}
                <img src="{{ photo.image_file.url }}" alt="Post image">
            {% elif photo.image_url %}
                <img src="{{ photo.image_url }}" alt="Post image">
            {% else %}
                <!-- if no photos available, show No Image -->
                <img src="{% static 'images/no_image.png' %}" alt="No image available">
            {% endif %}
        {% endfor %}

        <br>

        <!-- Like/Unlike button visible only for authenticated users other than the owner -->
        {% if request.user.is_authenticated and request.user != post.profile.user %}
            {% if is_liked %}
                <!-- If post already liked by the logged-in user -->
                <form action="{% url 'unlike_post' post.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Unlike</button>
                </form>
            {% else %}
                <!-- If post not liked yet by the logged-in user -->
                <form action="{% url 'like_post' post.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Like ❤️</button>
                </form>
            {% endif %}
        {% endif %}

        <!-- Display likes and count of likes -->
        {% if post.get_num_likes == 1 %}
            Liked by <strong>@{{ post.get_likes.0.profile.username }}</strong>
        {% elif post.get_num_likes > 1 %}
            Liked by <strong>@{{ post.get_likes.0.profile.username }}</strong> and <strong>{{ post.get_num_likes|add:"-1" }}</strong> others
        {% else %}
            No one has liked this post
        {% endif %}

        <br>

        <!--Display comments after the photos-->
        {% for comment in post.get_all_comments %}
            <br>{{ comment }}
        {% endfor %}
    </div>

    <p>Posted on {{ post.timestamp }}</p>
</main>

{% endblock %}

mini_insta/templates/mini_insta/update_profile_form.html
<!-- mini_insta /update_profile_form.html
# File: update_profile_form.html
# Author: Luisa Vazquez Usabiaga (lvu@bu.edu), 10/09/2025
# Description: display the HTML form to update a Post
-->

    {% extends 'mini_insta/base.html' %}
    {% load static %}
    
    {% block content %}
    <h2>Update a Profile</h2>
    
    <form method = 'POST' enctype="multipart/form-data">
    {% csrf_token %}
    
    <!-- Diplay fields from form for Profile-->
        <table>
        {% for field in form %}
        <tr>
            <th>{{field.name}}</th>
            <td>{{field}}</td>
        </tr>
        {% endfor %}
        <tr>
            <td></td>
             <!-- Form to submit/cancel request -->
            <td>
                <button type="submit" name="update_profile" class="update-btn" 
                style="border:none; background:none; cursor:pointer;">
                <img src="{% static 'images/update_icon.png' %}" 
                    alt="Update" 
                    class="icon"
                    style="width:100px; height:auto; display:inline-block; object-fit:contain;">
                </button>
                <a href="{{ form.instance.get_absolute_url }}" class="cancel-btn">
                    <img src="{% static 'images/cancel_icon.png' %}" alt="Cancel" class="icon" style="width:100px; height:auto; display:inline-block; object-fit:contain;">  
                </a>
                

            </td>
        </tr>
        </table>
    </form>
    
    {% endblock %}